{% set version = "1.6.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mixedcca
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mixedCCA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mixedCCA/mixedCCA_{{ version }}.tar.gz
  sha256: bb2974df62d62ce8c061c2b9a1ff09a571cb546c7ceb2e49e087483ecfa0571d

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - r-base
    - r-mass
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-fmultivar
    - r-irlba
    - r-mnormt
    - r-pcapp
    - r-latentcor >=2.0.1
  run:
    - r-base
    - r-mass
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-fmultivar
    - r-irlba
    - r-mnormt
    - r-pcapp
    - r-latentcor >=2.0.1

test:
  commands:
    - $R -e "library('mixedCCA')"           # [not win]
    - "\"%R%\" -e \"library('mixedCCA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mixedCCA
  license: GPL-3.0-only
  summary: "Semi-parametric approach for sparse canonical correlation analysis which can handle mixed data types: continuous, binary and truncated continuous. Bridge functions are provided to connect Kendall's tau to latent correlation under the Gaussian copula model. The methods are described in Yoon, Carroll and Gaynanova (2020) <doi:10.1093/biomet/asaa007> and Yoon, Mueller and Gaynanova (2021) <doi:10.1080/10618600.2021.1882468>."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler
